-- Durable, aggregatable recommendations generated by the TrafficAgent.
-- Apply this migration before enabling the traffic decision endpoints.
CREATE TABLE IF NOT EXISTS public.traffic_decisions (
    id bigserial PRIMARY KEY,
    agent character varying(100) NOT NULL,
    decision_type character varying(80) NOT NULL,
    location character varying(255),
    severity character varying(20),
    recommendation text NOT NULL,
    reason text,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    status character varying(30) NOT NULL DEFAULT 'RECOMMENDED',
    source character varying(50) NOT NULL DEFAULT 'DEMONSTRATION',
    outcome character varying(30) NOT NULL DEFAULT 'PENDING',
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_traffic_decisions_created_at ON public.traffic_decisions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_traffic_decisions_type_status ON public.traffic_decisions (decision_type, status);
